---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: couchdb-production-pv-0
spec:
  storageClassName: local-path
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/opt/couchdb-production/data"
    type: DirectoryOrCreate

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: couchdb-production-pv-1
spec:
  storageClassName: local-path
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/opt/couchdb-production/data"
    type: DirectoryOrCreate